import esbuild from "esbuild";
import process from "node:process";
import { builtinModules } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the project's repository.
*/`;
const production = process.argv[2] === "production";
const projectDirectory = dirname(fileURLToPath(import.meta.url));

const context = await esbuild.context({
	absWorkingDir: projectDirectory,
	banner: { js: banner },
	entryPoints: [join(projectDirectory, "src", "main.ts")],
	bundle: true,
	external: ["obsidian", "electron", "@codemirror/state", "@codemirror/view", ...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: production ? false : "inline",
	treeShaking: true,
	outfile: join(projectDirectory, "main.js")
});

if (production) {
	await context.rebuild();
	await context.dispose();
} else {
	await context.watch();
}
